namespace CryptoMarketDataResearchEngine.Models;

public sealed record RawDepthRow(
    DateTime EventTs,
    DateTime LocalReceiveTs,
    string Symbol,
    long FirstUpdateId,
    long LastUpdateId,
    string BidUpdatesJson,
    string AskUpdatesJson,
    int BidUpdateCount,
    int AskUpdateCount,
    double ReceiveLatencyMs,
    string RawPayloadJson);

public sealed record RawAggTradeRow(
    DateTime EventTs,
    DateTime TradeTs,
    DateTime LocalReceiveTs,
    string Symbol,
    long AggTradeId,
    long FirstTradeId,
    long LastTradeId,
    double Price,
    double Quantity,
    bool BuyerIsMaker,
    string TradeSide,
    double ReceiveLatencyMs,
    string RawPayloadJson);

public sealed record BookChangeRow(
    DateTime EventTs,
    DateTime LocalReceiveTs,
    string Symbol,
    string EventType,
    string Side,
    double Price,
    double PreviousQuantity,
    double NewQuantity,
    double DeltaQuantity,
    double AbsoluteDeltaQuantity,
    bool IsBestLevel,
    long FirstUpdateId,
    long LastUpdateId,
    long BookLastUpdateId);

public sealed record SnapshotRow(
    DateTime EventTs,
    DateTime LocalReceiveTs,
    string Symbol,
    long LastUpdateId,
    string BidsJson,
    string AsksJson,
    int BidLevelCount,
    int AskLevelCount,
    bool DepthSynchronized,
    long ResyncCount);

public sealed record FeatureRow(
    DateTime EventTs,
    DateTime LocalComputeTs,
    string Symbol,
    int FeatureIntervalMs,
    int RollingWindowMs,
    long BookLastUpdateId,
    double BestBid,
    double BestAsk,
    double Midprice,
    double Spread,
    double Microprice,
    double BestBidSize,
    double BestAskSize,
    double TotalBidDepthL5,
    double TotalAskDepthL5,
    double BidL1Price,
    double BidL2Price,
    double BidL3Price,
    double BidL4Price,
    double BidL5Price,
    double BidL1Size,
    double BidL2Size,
    double BidL3Size,
    double BidL4Size,
    double BidL5Size,
    double AskL1Price,
    double AskL2Price,
    double AskL3Price,
    double AskL4Price,
    double AskL5Price,
    double AskL1Size,
    double AskL2Size,
    double AskL3Size,
    double AskL4Size,
    double AskL5Size,
    double OrderFlowImbalance,
    double BuyTradeVolumeWindow,
    double SellTradeVolumeWindow,
    double TradeImbalance,
    double LimitAddBidWindow,
    double LimitAddAskWindow,
    double CancelBidWindow,
    double CancelAskWindow);
